# Site settings
baseURL = "https://jonathanngguyen.me"
languageCode = "en-US"
title = "Jonathan Nguyen"
theme = "hugo-split-theme"
disableKinds = ["page", "section", "taxonomy", "taxonomyTerm", "RSS", "sitemap", "robotsTXT"]

# Enter your tracking code to enable Google Analytics
googleAnalytics = "UA-115030409-1"

[params]

  # Metadata for search engines and social sharing
  name = "Jonathan Nguyen"
  description = "Jonathan Nguyens portfolio website."
  shareImage = "images/background-edit-gradient-2-min.jpg"
  twitterHandle = ""
  logosrc = "images/logo-min.png"

  # Favicon
  favicon = "favicon.ico"

  # Copyright
  copyright = "&copy;2020 Jonathan Nguyen"


  # Section - Content
  [params.content]
    name = "Jonathan Nguyen"
    tagline = "Software Engineer at IBM"
    bio = "👋 Hi! I’m just someone who has fun learning and making computers talk to other computers. Feel free to take a look at my [resume](jonathanNguyenSoftwareResume.pdf) or view my complete profile on [LinkedIn!](//www.linkedin.com/in/jonthnngyn)"

  # Section - Visual
  [params.visual]

    # Image
    [params.visual.image]
      enable = true
      file = "images/background-edit-gradient-2-min.jpg"
      position = "center center"

    # Video
    [params.visual.video]
      enable = false
      mute = true
      file = "videos/background.mp4"
      # youtubeId = "dk9uNWPP7EA"

  # Links
  #
  # Links List #1
    [[params.links]]
      [params.links.list1]
        heading = "Experience"

        [[params.links.list1.link]]
          text = "IBM"
          url = "//www.ibm.com/products/db2-data-management-console"

        [[params.links.list1.link]]
          text = "Sony PlayStation"
          url = "//www.playstation.com/en-us/explore/playstation-now/"

        [[params.links.list1.link]]
          text = "Cox Automotive - Kelley Blue Book"
          url = "//www.kbb.com"

  # Links List #2
  [[params.links]]
    [params.links.list2]
      heading = "Projects"
      [[params.links.list2.link]]
        text = "PokeARena"
        url = "//devpost.com/software/citrus-hacks-2018"

      [[params.links.list2.link]]
        text = "Instanurse"
        url = "//devpost.com/software/instanurse"

      [[params.links.list2.link]]
        text = "VRoom"
        url = "//devpost.com/software/vroom-ofcbn0"

      [[params.links.list2.link]]
        text = "ML Food Journal Research"
        url = "//dl.acm.org/doi/abs/10.1145/3264996.3265000"

      [[params.links.list2.link]]
        text = "More >"
        url = "//www.github.com/Tunsy"

  # Links List #3
  [[params.links]]
    [params.links.list3]
      heading = "Leadership"

      [[params.links.list3.link]]
        text = "VGDC"
        url = "//sites.google.com/view/vgdcuci/home?authuser=0"

      [[params.links.list3.link]]
        text = "FIRST Robotics"
        url = "//www.fremontrobotics.com/"

      [[params.links.list3.link]]
        text = "Developers' Guild"
        url = "//github.com/DevelopersGuild"

 

  # The original template is released under the Creative Commons Attribution 3.0 License.
  # Please keep the original attribution link when using for your own project.
  # If you'd like to use the template without the attribution, you can check out
  # the license option via the template author's website: https://onepagelove.com/split
